# Generated by Django 5.2.8 on 2025-11-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='E_Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pagamento', models.CharField(max_length=50)),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('taxa_adm', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
