# Generated by Django 5.2.8 on 2025-11-26 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookmasters_app', '0001_initial'),
    ]

    operations = [
    ]

from django.db import migrations
from cookmasters_app.models import E_Receita 

def criar_tags_iniciais(apps, schema_editor):
    E_Tag = apps.get_model('cookmasters_app', 'E_Tag') 
    
    tags_para_criar = E_Receita.TAGS_PADRAO
    
    for nome in tags_para_criar:
        E_Tag.objects.get_or_create(nome=nome)

class Migration(migrations.Migration):

    dependencies = [
        ('cookmasters_app', '0001_initial'), 
    ]

    operations = [
        migrations.RunPython(criar_tags_iniciais),
    ]