# Generated by Django 3.2.12 on 2025-11-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookmasters_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_receita',
            name='ingredientes',
            field=models.ManyToManyField(related_name='receitas', to='cookmasters_app.E_Ingrediente'),
        ),
    ]
