# Generated by Django 3.2.12 on 2025-11-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookmasters_app', '0002_e_receita_ingredientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_receita',
            name='modo_de_preparo',
            field=models.TextField(default='Modo de preparo não informado'),
            preserve_default=False,
        ),
    ]
