# Generated by Django 5.2.8 on 2025-11-13 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookmasters_app', '0002_e_receita_ingredientes'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='e_usuariogeral',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='e_usuariogeral',
            name='username',
        ),
    ]
