# Generated by Django 3.2.12 on 2025-11-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookmasters_app', '0003_e_receita_modo_de_preparo'),
    ]

    operations = [
        migrations.CreateModel(
            name='E_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='e_receita',
            name='tag',
        ),
        migrations.AlterField(
            model_name='e_receita',
            name='modo_de_preparo',
            field=models.TextField(default='Sem modo de preparo informado'),
        ),
        migrations.AddField(
            model_name='e_receita',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='receitas', to='cookmasters_app.E_Tag'),
        ),
    ]
