# Generated by Django 5.2.8 on 2025-11-13 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookmasters_app', '0003_alter_e_usuariogeral_managers_and_more'),
        ('cookmasters_app', '0004_auto_20251113_1724'),
    ]

    operations = [
    ]
