# Generated by Django 5.2.8 on 2025-11-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookmasters_app', '0005_merge_20251113_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_chefe',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='Fotos/'),
        ),
        migrations.AlterField(
            model_name='e_chefe',
            name='Numero_conta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='e_chefe',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='e_chefe',
            name='nome_do_banco',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='e_chefe',
            name='numero_agencia',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
