# Generated by Django 5.2.8 on 2025-11-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookmasters_app', '0006_e_chefe_foto_alter_e_chefe_numero_conta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_receita',
            name='dificuldade',
            field=models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil')], default='facil', max_length=10),
        ),
        migrations.AddField(
            model_name='e_receita',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_receitas'),
        ),
        migrations.AddField(
            model_name='e_receita',
            name='tempo_preparo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='e_chefe',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_chefes'),
        ),
    ]
