# Generated by Django 5.2.8 on 2025-11-21 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookmasters_app', '0007_e_receita_dificuldade_e_receita_foto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='E_Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('consumidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookmasters_app.e_consumidor')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookmasters_app.e_receita')),
            ],
        ),
    ]
