# Generated by Django 5.2.8 on 2025-11-21 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookmasters_app', '0008_e_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_compra',
            name='pagamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cookmasters_app.e_pagamento'),
        ),
        migrations.AlterField(
            model_name='e_pagamento',
            name='tipo_pagamento',
            field=models.CharField(choices=[('pix', 'PIX'), ('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito')], default='pix', max_length=20),
        ),
    ]
