# Generated by Django 5.2.8 on 2025-11-21 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookmasters_app', '0009_e_compra_pagamento_alter_e_pagamento_tipo_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e_avaliacoes',
            name='consumidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookmasters_app.e_consumidor'),
        ),
    ]
