# Generated by Django 5.2.8 on 2025-11-24 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookmasters_app', '0010_alter_e_avaliacoes_consumidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e_compra',
            name='receita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='cookmasters_app.e_receita'),
        ),
    ]
