# Generated by Django 5.2.8 on 2025-11-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookmasters_app', '0011_alter_e_compra_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e_usuariogeral',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
