# Generated by Django 5.2.8 on 2025-11-08 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receitas', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='e_avaliacoes',
            name='consumidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='e_receita',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.e_chefe'),
        ),
        migrations.AddField(
            model_name='e_avaliacoes',
            name='receita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.e_receita'),
        ),
        migrations.AddField(
            model_name='receitaingrediente',
            name='ingrediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.e_ingrediente'),
        ),
        migrations.AddField(
            model_name='receitaingrediente',
            name='receita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.e_receita'),
        ),
        migrations.AddField(
            model_name='e_receita',
            name='ingredientes',
            field=models.ManyToManyField(through='receitas.ReceitaIngrediente', to='receitas.e_ingrediente'),
        ),
        migrations.AlterUniqueTogether(
            name='receitaingrediente',
            unique_together={('receita', 'ingrediente')},
        ),
    ]
