# Generated by Django 5.2.8 on 2025-11-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='e_ingrediente',
            name='tipo',
        ),
        migrations.AddField(
            model_name='e_receita',
            name='tag',
            field=models.CharField(blank=True, choices=[('LOW CARB', 'Low Carb'), ('SEM LACTOSE', 'Sem Lactose'), ('SEM GLUTEN', 'Sem Glúten'), ('VEGANO', 'Vegano'), ('VEGETARIANO', 'Vegetariano'), ('LOW FAT', 'Low Fat'), ('HIGH PROTEIN', 'High Protein'), ('SEM SOJA', 'Sem Soja')], max_length=50),
        ),
    ]
