# Generated by Django 5.2.8 on 2025-11-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e_chefe',
            name='Nota',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='e_chefe',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
